# Generated by Django 4.1.1 on 2022-10-04 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Название региона',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Название навыка',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Название вакансии',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='VacSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('percent', models.FloatField()),
                ('id_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoParserApp.skills')),
                ('id_vac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoParserApp.vacancy')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Count_vac', models.IntegerField()),
                ('Up', models.FloatField()),
                ('Down', models.FloatField()),
                ('Area_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoParserApp.area')),
                ('Vac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoParserApp.vacancy')),
            ],
        ),
    ]
