# Generated by Django 4.1.1 on 2022-09-17 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoParserApp', '0002_remove_request_skill_name_alter_skills_skill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='Skill_name',
        ),
        migrations.AddField(
            model_name='request',
            name='Skill_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DjangoParserApp.skills'),
            preserve_default=False,
        ),
    ]
