# Generated by Django 4.1.1 on 2022-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoParserApp', '0003_remove_request_skill_name_request_skill_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='Count_vac',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Down',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='Up',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
